[package]
name = "gauss"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"
bencher = { path = "../bencher" }
cannon = { path = "../cannon" }
scalar = { path = "../scalar" }
